export const FETCH_CAREERS = 'FETCH_CAREERS';
export const FETCH_CAREERS_PENDING = 'FETCH_CAREERS_PENDING';
export const FETCH_CAREERS_FULFILLED = 'FETCH_CAREERS_FULFILLED';
export const FETCH_CAREERS_REJECTED = 'FETCH_CAREERS_REJECTED';
